services:
  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile.frontend
    ports:
      - "8000:8000"
    volumes:
      - frontend_build:/app/build
    environment:
      NODE_ENV: production
    networks:
      - mynetwork

  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - mynetwork

volumes:
  frontend_build:

networks:
  mynetwork:
    driver: bridge
