services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/build
    environment:
      NODE_ENV: production
    networks:
      - mynetwork

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - static_volume:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - mynetwork

volumes:
  static_volume:

networks:
  mynetwork:
    driver: bridge

