services:
  frontend:
    container_name: frontendapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
    volumes:
      - ./core:/core

  nginx:
    build:
      context: ./nginx
      dockerfile: DockerFile
    ports:
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./core/static:/static
    depends_on:
      - frontend