services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8000:80"
    environment:
      NODE_ENV: production
    networks:
      - mynetwork
