FROM node:20-alpine as build
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --frozen-lockfile
COPY . .
RUN chmod +x node_modules/.bin/webpack
RUN chmod -R 777 /app/build
RUN npm run build:prod

FROM nginx:stable-alpine

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/ssl /etc/nginx/ssl

VOLUME /usr/share/nginx/html

EXPOSE 80 443 8000

CMD ["nginx", "-g", "daemon off;"]