filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
    fields:
      service: frontend_geant

processors:
  - drop_fields:
      fields: ["agent", "input", "ecs", "log.offset"]

output.logstash:
  hosts: ["${ELK_IP}:5044"]
